### ISSUE TITLE
Solve LeetCode problems for Hacktoberfest 2020

### ISSUE THREAD

**Issue by miichack** [miichack/Hacktoberfest-2020-LeetCode-Problems#2]
Solve any LeetCode problem found at [https://leetcode.com/problemset/all/](https://leetcode.com/problemset/all/) and commit it to this repository by creating a pull request.

Please read the README file before contributing

**Comment by chetangawai** [comment]
@miikkasaxlund Can you please assign me this ticket?

**Comment by miikkasaxlund** [comment]
@chetangawai You can just create a pull request to this repository, as I will surely merge any valid requests. I will keep this issue open so that other people may find this repository during the Hacktoberfest

**Comment by ITES7321** [comment]
Hi! can I contribute to this repo? Thanks!

**Comment by miikkasaxlund** [comment]
@ITES7321 Sure you can!
