### ISSUE TITLE
Merging of Pending Pull Requests created during Hactoberfest

### ISSUE THREAD

**Issue by ashk3301** [miichack/Hacktoberfest-2020-LeetCode-Problems#95]
I had submitted a PR 6 days ago for completing the Hacktoberfest challenge. I know you could be busy and that's why the pending PRs have not been merged but I would request you to please merge the valid pending PRs at your earliest convenience.

**Comment by miichack** [comment]
I am so sorry about the delay, I have been too busy this whole week. I will merge all pending requests later today!
